name: desmiles
channels:
  - fastai
  - pytorch
  - conda-forge
  - defaults
  - rdkit
dependencies:
  - python=3.7
  - pip
  - pytorch=1.0.0
  - fastai=1.0.55
  - mkl=2019
  - numpy=1.18
  - scipy=1.4.1
  - pandas=1.03
  - rdkit=2018.09.1
  - pytest=5.4.1
  - seaborn=0.10.1
  - pkgs/main::sentencepiece
  - jupyter=1.0.0
  - pip:
    - "git+https://github.com/DEShawResearch/DESMILES@1.0"
    - scikit-learn==0.19.2
